### ISSUE TITLE
Amend so that Discourse can be opened within Nextcloud?

### ISSUE THREAD

**Issue by fml-isak** [soudis/discoursesso#18]
I don't know 'bout y'all. But since the "[app page](https://apps.nextcloud.com/apps/discoursesso)" for this app stated that 
> "Discourse can then be used as an external app inside Nextcloud"

I was under the impression that this would be possible, aside from the ability to login at Nextcloud, and not having to log in when visiting Discourse. 

Currently, I cannot open a Discourse forum within Nextcloud (as Discourse seems to forbid it from being embedded within iframes). I found an [old Discourse plugin](https://github.com/BeXcellent/discourse-allowiframe/) attempting to allow it to be iframed. If something similar would be possible to integrate with the SSO function, that would just be fantastic. 

Thank you for the SSO plugin so far!

**Comment by soudis** [comment]
You're right the app info text is misleading. In the beginning I was using discourse really inside nextcloud with the iframe embedding. To make this work I used my own plugin: https://github.com/soudis/discourse-allow-same-origin

But I ended up setting discourse to be opened in a separate tab, because it lead to small problems here and there and the plugin I made for discourse is also a rather dirty hack.

**Comment by fml-isak** [comment]
Alright, thank you @soudis for that answer! I tried the plugin I linked, which seem to have crashed my instance. Might try yours though!! Thanks for the link! 
Too bad there is no official integration into the Nextcloud. But I suppose I'll get used to using it externally. 

All the best!
